<?php

/**
 * @file
 */

define('CASALUIS_MENU_VID', 2);


/**
 * Implements hook_menu().
 */
function casaluis_menu_menu() {
  $path_prefix = 'menu';
  
  $terms = taxonomy_get_tree(CASALUIS_MENU_VID);
  dsm($terms);
  $items[$path_prefix] = array(
      'title' => t('Menu'),
      'description' => 'Lists the Casa Luis menu.',
      'access arguments' => array('access content'),
      'page callback' => 'drupal_goto',
      'page arguments' => array('menu/'. $terms[0]->tid),
    );
  foreach ($terms as $term) {
    $items[$path_prefix .'/'. $term->tid] = array(
      'title' => $term->name,
      'description' => 'Lists all the menu items in '. $term->name .'.',
      'access arguments' => array('access content'),
      'page callback' => 'views_embed_view',
      'page arguments' => array('menu_list', 'default', $term->tid),
      'type' => MENU_LOCAL_TASK,
    );
  }
  
  return $items;
}



/****  Internal helper functions ********/

//dsm(taxonomy_get_tree(CASALUIS_MENU_VID));