<?php

/**
 * @file
 * Checks pages for changes
 */

include_once 'check_page.crud.inc';

define('CHECK_PAGE_ADMIN_PATH', 'admin/config/check-page');

/**
 * Implements hook_menu().
 */
function check_page_menu() {
  // Make "Foo settings" appear on the admin Config page
  $items[CHECK_PAGE_ADMIN_PATH] = array(
    'title' => 'Check Page settings',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer check page'),
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/config/check-page/list'),
  );
  // Make "Tab 1" the main tab on the "Foo settings" page
  $items[CHECK_PAGE_ADMIN_PATH .'/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer check page'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('check_page_list_form'),
    'file' => 'check_page.admin.inc',
    'weight' => -10,
  );
  // Make an additional tab called "Tab 2" on "Foo settings"
  $items[CHECK_PAGE_ADMIN_PATH .'/add'] = array(
    'title' => 'Add',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer check page'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('check_page_add_form'),
    'file' => 'check_page.admin.inc',
  );
  // Make an additional tab called "Tab 2" on "Foo settings"
  $items[CHECK_PAGE_ADMIN_PATH .'/cron'] = array(
    'title' => 'Cron',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer check page'),
    // Page callback and theme callback will be inherited from
    // 'admin/config/system/foo', if not specified here to override.
    // Need to add access callback or access arguments.
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function check_page_permission() {
  return array(
    'administer check page' => array(
      'title' => t('Administer Check Page'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function check_page_theme($existing, $type, $theme, $path) {
  return array(
    'check_page_pages_table' => array(
      'variables' => array('pages' => NULL),
      'file' => 'check_page.theme.inc',
    ), 
  );
}

/****  Internal helper functions ********/

function _check_page_check_pages($pages, $first_time = FALSE) {
  
  foreach ($pages as $page) {
    $cpid = $page->cpid;
    $contents = file_get_contents($page->url);
    $page->flag = 0;
    if (isset($page->data)) {
      if ($page->data != $contents) {
        $page->flag = 1;
      }
    }
    $page->data = $contents;
    _check_page_update_page($page);
  }
  
}